# Generated by Django 5.0.2 on 2024-11-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='deskripsi',
        ),
    ]
