# Generated by Django 5.0.2 on 2024-11-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0003_rename_harga_barang_hj_barang_hpp'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='jenis',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
