# Generated by Django 5.0.2 on 2024-11-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0005_remove_barang_stok'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barang',
            options={'ordering': ['jenis', 'order']},
        ),
        migrations.AddField(
            model_name='barang',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
