# Generated by Django 5.0.2 on 2024-11-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stok', '0006_alter_barang_options_barang_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
